services:
  db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/pgdata

  db-interface:
    build: ./db-interface
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  crawler:
    build: ./crawler
    depends_on:
      - db-interface

volumes:
  db_data: