services:
  db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/pgdata

  db-interface:
    build: ./db-interface
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  crawler:
    build: ./crawler
    depends_on:
      - db-interface

  web-explorer:
    build: ./web-explorer
    depends_on:
      - db-interface

  webapp:
    build: ./webapp
    ports:
      - "8000:8000"
    depends_on:
      - db-interface
    env_file:
      - .env
    volumes: # !!! WARNING !!!: This is only for development purposes
      - ./webapp/static:/app/static # !!! WARNING !!!: This is only for development purposes
      - ./webapp/templates:/app/templates # !!! WARNING !!!: This is only for development purposes

volumes:
  db_data: